### ISSUE TITLE
sudo make install error

### ISSUE THREAD

**Issue by xue-fei** [aleh/pocketchip-jwmrc#1]
x11/xft/xft.h no such file

**Comment by tslpre** [comment]
This is because newer releases (ie. Buster) require the installation of libxft-dev:

sudo apt install libxft-dev

**Comment by xue-fei** [comment]
> This is because newer releases (ie. Buster) require the installation of libxft-dev:
> 
> sudo apt install libxft-dev

Thank you.

**Comment by aleh** [comment]
@tslpre, @xue-fei: Thanks guys!
