### ISSUE TITLE
Install on Buster still boots to pocket-home

### ISSUE THREAD

**Issue by mackemint** [aleh/pocketchip-jwmrc#2]
I cloned the repo, installed the libxft-dev and ran make install. 

No error messages and on reboot I’m greeted by the Debian login screen. 

Adding autologin-in-background = true in lightdm returns me to pocket-home screen without login screen but no jwm. :/

**Comment by mackemint** [comment]
Correction: i must have added a reboot after my make install. 
I’m now getting the error message 
    error: could not open display :0

**Comment by aleh** [comment]
Hey! Unfortunately I don't have a device with Buster now to check it out.

**Comment by mackemint** [comment]
Ok fair enough. I might try installing it on a fresh system and see if it survives updating. Cheers!
